name: 'SmartCheck'
image: 'smartbugs/smartcheck'
command: '-p'
type: flag
flag:
  'SOLIDITY_ADDRESS_HARDCODED': 10
  'SOLIDITY_ARRAY_LENGTH_MANIPULATION': 3
  'SOLIDITY_BALANCE_EQUALITY': 10
  'SOLIDITY_BYTE_ARRAY_INSTEAD_BYTES': 10
  'SOLIDITY_CALL_WITHOUT_DATA': 1
  'SOLIDITY_CONSTRUCTOR_RETURN': 2
  'SOLIDITY_DELETE_ON_DYNAMIC_ARRAYS': 10
  'SOLIDITY_DEPRECATED_CONSTRUCTIONS': 10
  'SOLIDITY_DIV_MUL': 3
  'SOLIDITY_DO_WHILE_CONTINUE': 10
  'SOLIDITY_ERC20_APPROVE': 10
  'SOLIDITY_ERC20_FUNCTIONS_ALWAYS_RETURN_FALSE': 10
  'SOLIDITY_ERC20_INDEXED': 10
  'SOLIDITY_ERC20_TRANSFER_SHOULD_THROW': 10
  'SOLIDITY_EXACT_TIME': 8
  'SOLIDITY_EXTRA_GAS_IN_LOOPS': 10
  'SOLIDITY_FUNCTION_RETURNS_TYPE_AND_NO_RETURN': 10
  'SOLIDITY_GAS_LIMIT_IN_LOOPS': 5
  'SOLIDITY_INCORRECT_BLOCKHASH': 10
  'SOLIDITY_LOCKED_MONEY': 10
  'SOLIDITY_MSGVALUE_EQUALS_ZERO': 10
  'SOLIDITY_OVERPOWERED_ROLE': 10
  'SOLIDITY_PRAGMAS_VERSION': 10
  'SOLIDITY_PRIVATE_MODIFIER_DOES_NOT_HIDE_DATA': 10
  'SOLIDITY_REDUNDANT_FALLBACK_REJECT': 10
  'SOLIDITY_REVERT_REQUIRE': 10
  'SOLIDITY_REWRITE_ON_ASSEMBLY_CALL': 10
  'SOLIDITY_SAFEMATH': 3
  'SOLIDITY_SEND': 4
  'SOLIDITY_SHOULD_NOT_BE_PURE': 10
  'SOLIDITY_SHOULD_NOT_BE_VIEW': 10
  'SOLIDITY_SHOULD_RETURN_STRUCT': 10
  'SOLIDITY_TRANSFER_IN_LOOP': 5
  'SOLIDITY_TX_ORIGIN': 2
  'SOLIDITY_UINT_CANT_BE_NEGATIVE': 3
  'SOLIDITY_UNCHECKED_CALL': 4
  'SOLIDITY_UNUSED_FUNCTION_SHOULD_BE_EXTERNAL': 10
  'SOLIDITY_UPGRADE_TO_050': 10
  'SOLIDITY_USING_INLINE_ASSEMBLY': 10
  'SOLIDITY_VAR': 3
  'SOLIDITY_VAR_IN_LOOP_FOR': 3
  'SOLIDITY_VISIBILITY': 10
  'SOLIDITY_WRONG_SIGNATURE': 10